# Introduction to the NumPy (Numerical Python) Library

As discussed in the tutorial on Libraries, **NumPy**, together with **Matplotlib** and **SciPy**, form the backbone of scientific computing in Python. NumPy is covered in this notebook. Matplotlib is covered in a separate notebook this week. SciPy will be covered later. You may be interested in the [Wikipedia page](https://en.wikipedia.org/wiki/NumPy) and the [NumPy home page](https://numpy.org/).

> "NumPy aims to provide an array object that is up to 50x faster that traditional Python lists." -- [w3schools.com](https://www.w3schools.com/python/numpy_intro.asp)


---
## Array creation

First to clarity terminology 

- 1D arrays have one index, as in $(x_0, x_1, \cdots, x_k, \cdots, x_{n-1})$, where the index $k$ starts from $0$. Hence, these arrays are the same as vectors and we use either term.

- 2D arrays have two indices. These are like matrices with elements $a_{kl}$, the first index corresponding to the row and the second to the column. 

- In this context, floating point numbers and complex numbers (and possibly integers) are referred to as scalars. They have no index. 

One can consider higher-dimensional arrays, but we will not need them.

In order to use NumPy, you first have to import it. Typically we do this and give NumPy the alias np:

In [1]:
import numpy as np

(The above line will probably appear in every subsequent notebook you use in this module.)


We then can create the common arrays that we will need

In [3]:
v = np.array([1, 2, 3])               # create vector from a list (we won't use much)
w = np.zeros(3)                       # create a vector of length 3 with zeros
A = np.zeros((2, 3))                  # create a 2 x 3 matrix full of zeros
B = np.ones((3, 4))                   # create a 3 x 4 matrix full of ones 
Id = np.eye(4)                        # create a 4 x 4 identity matrix

print("v =", v, "\n")
print("w =", w, "\n")
print("A =\n", A, "\n")
print("B =\n", B, "\n")
print("Id = \n", Id, "\n")

# Note "\n" prints an extra newline, used here to provide more readability

v = [1 2 3] 

w = [0. 0. 0.] 

A =
 [[0. 0. 0.]
 [0. 0. 0.]] 

B =
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Id = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



**Warning:**  If you are creating a vector, then you can just use `np.zeros(vector_length)`,  where `vector_length` is an integer. However, if you are creating an array with more than one dimension, then you need `np.zeros(shape)`, where `shape` is a tuple of integers. Hence we have
```
A = np.zeros((2, 3))
```
To make this clear, some people would explicitly use a keyword argument
```
A = np.zeros(shape=(2, 3))
```

It is easy to make a mistake of writing
```
A = np.zeros(2, 3)
```

**Exercise:** Edit the cell above to change `A = np.zeros((2, 3))` to `A = np.zeros(2, 3)`. Rerun the cell to see the error that is generated. Then re-edit cell to restore the correct version, but this time including the keyword `shape =`.

---
It is very common to want to know the shape of an array. This is available using `.shape` 

In [4]:
print("shape of v is:", v.shape)
print("shape of A:", A.shape)         

shape of v is: (3,)
shape of A: (2, 3)


What are the shapes of B and Id defined above? Edit the above cell to print these shapes and verify your answer.

---
Use .ndim to determine the number of dimensions for an array. 

In [ ]:
print("vector v has dimension", v.ndim)
print("matrix A has dimension", A.ndim)

All NumPy arrays have the same type `numpy.ndarray` independent of dimension

In [5]:
print("vector v has type", type(v))
print("matrix A has type", type(A))

vector v has type <class 'numpy.ndarray'>
matrix A has type <class 'numpy.ndarray'>


**If you are ever uncertain about the number of elements in your arrays, print their shapes!**

---
### regular arrays

We will often be interested in regular arrays of numbers. There are two standard ways to create such arrays. Use

- `np.arange` if you want a sequence of numbers with a specified `step`. The number of elements in the array is determined by `start`, `stop` and `step`.  Just as for the range type, **stop will not be included in the array**.

In [ ]:
a = np.arange(0, 10, 2)   # we want a simple step of 2
print(a)

- `np.linspace` if you want an array of numbers with a specified number of elements. The `step `is determined by `start`, `stop` and the number of element. **stop will be included in the array**.

In [6]:
b = np.linspace(0, np.pi, 10)   # we want 10 elements, including both 0 and pi
print(b)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


Note how with `np.linspace` this situation is easy. It would be more awkward with `np.arange` since `step` is not a simple value.  `np.linspace` can also return the step between elements (note the use of a keyword argument).

In [ ]:
b, step = np.linspace(0, np.pi, 10, retstep=True)
print("step = ", step)

---
## Demonstration matrix

Above we saw how to create matrices with zeros, ones, or the identity. It is useful to have a matrix with less trivial values for demonstrations. A common, useful example is illustrated in the next cell.

In [7]:
# Create a 3x4 matrix
A = np.arange(0,12).reshape(3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


You can see what is happening. np.arange is used to generate an array of values 0 thought 12. The `.reshape(3,4)` reshapes that linear array into a rectangular array, i.e. a matrix. Such matrices will appear in this module only for demonstrations. When needed, I will remind you where to copy the above example. 

---
## Indexing and slicing arrays

You access individual elements using square brackets `[ ]`. Recall that we also used square brackets for accessing elements of lists and strings. Indices always start at 0. As with lists, you can slice arrays to obtain portions of arrays. For vectors, you will not notice much difference between accessing elements of list and elements of a vector. 

Think about what the output of the cell below will be before running the cell. Then run the cell to confirm. 

In [10]:
v = np.arange(0,12)
print(v)
print(v[3])
print(v[-1])
print(v[0::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
3
11
[ 0  2  4  6  8 10]


If you did not get this correct, you may need to review slicing. In particular, recall how to access the last element. 

**Exercise:** Edit the cell above to print all the elements of v with odd index. Edit the cell to print all the elements of v in reverse order.

---

For matrices the comma `,` separates the two indices (the two dimensions). The way to think about the notation is: 

`A[ slicing rule , other slicing rule ]`

where both are any allowable slicing rule. 

In [11]:
A = np.arange(0,12).reshape(3,4)               # demonstration matrix
print(A, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



Now you have matrix `A` to look at, think about what the output of the cell below will be before running the cell. Then run the cell to confirm.

In [14]:
# Indexing individual elements (trivial slicing)
print(A[0, 0])
print(A[1, 2])
print()

# Slicing to obtain rows or columns
print(A[0,:])
print(A[-1,:])
print(A[:,1])
print()

# submatrix of the matrix 
print(A[0:2, 0:2], "\n")

0
6

[0 1 2 3]
[ 8  9 10 11]
[1 5 9]

[[0 1]
 [4 5]] 



(Unfortunately the column of `A` with values `1 5 9` is displayed in the form of a row. There are ways to change this, but they are too complicated and this is not sufficiently important.)  

We will only rarely need anything more complicated than what is shown above, but you need to be able to read and work with slicing. You should definitely be able to reference things like first row, all columns, last row all columns etc. 

As always, printing is your friend. 

---
## Standard operations with arrays

The rule is that when you operate on arrays, the operation applies to all elements, one after the other. This is known as acting **elementwise**. 

In [15]:
a = np.arange(7)
print("a is", a)
print("the double of each element of a is", 2 * a)
print("the square of each element of a is", a**2)

b = np.array([1, 2, 3])
c = np.array([2, 1, 4])

print("b is", b)
print("c is", c)
print("b + c is", b + c)
print("b * c is", b * c)

a is [0 1 2 3 4 5 6]
the double of each element of a is [ 0  2  4  6  8 10 12]
the square of each element of a is [ 0  1  4  9 16 25 36]
b is [1 2 3]
c is [2 1 4]
b + c is [3 3 7]
b * c is [ 2  2 12]


**Exercise:** Insert a line following the "the square of each element of a" line in which you print 2 to the power a.  power `2**a`. 

---
## NumPy mathematical functions

The NumPy library includes all the basic [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html) you would want: e.g. $\cos, \sin, \log, \exp, \sqrt{~} ~,$ etc. These functions act elementwise on numpy arrays. NumPy also provides an accurate approximation to $\pi$ via `np.pi`.


In [ ]:
# generate a regular array of points between 0 and 4
x = np.linspace(0, 4, 101)

# generate arrays from acting with functions on those x values
p = x**2
q = np.sqrt(x)
y = np.exp(x)
w = np.log(y)

# generate a regular array of points between 0 and 2pi
t = np.linspace(0, 2*np.pi, 101) 

# generate array cos(t)
f = np.cos(t)                      

# Such arrays will be plotted when we get to matplotlib

---
## Short list of useful NumPy functions other than standard maths functions

- `np.mean(a)` computes the arithmetic mean of the elements of `a`.
- `np.maximum(x1, x2)` elementwise maximum of `x1` and `x2`.  
- `np.minimum(x1, x2)` elementwise minimum of `x1` and `x2`.  
- `np.amax(a)` returns the maximum element of the array `a`.
- `np.amin(a)` returns the minimum element of the array `a`. 
- `np.linalg.norm(x)` computes the length (norm) of a vector. 

Note the difference between `np.maximum` and `np.amax` and between `np.minimum` and `np.amin`

You can read details in the NumPy documentation: [np.maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html)
and [np.amax](https://numpy.org/doc/stable/reference/generated/numpy.amax.html)

Examples will be given and aspects will be discussed as needed.

---
## Vector dot product and matrix product

There are ways to compute the 
dot product between 1D arrays as though they are vectors, or 
to multiply 2D arrays as though they are matrices.

These types of operations can dominate many numerical schemes. We will not have any need for these initially. You should be aware that they exist. We will return to these as needed.

---
## Copying arrays: a warning

If you want to copy an array, you should use `.copy()`

```
a = np.array([1,2,3])
b = a.copy()
```

If you just try assignment `b = a`, `b` will not be a full, independent copy of `a`. 


In [ ]:
a = np.array([1, 2, 3])

# assign b the value of a:
b = a
print(a, b)

# changing a will change b also
a[1] = 0
print(a, b, "\n")

# use .copy to get a true copy
b = a.copy()
print(a, b)
a[1] = 2
print(a, b)

You might think this would lead to lots of difficulties for us, but in fact it does not, at least I hope. We may come back to this.

---

## The Zero Trick

(We just made up this name so don't search for it elsewhere.) Suppose we have an np.array `c` and we want another np.array `d` of the same size but initialised to zero. We could use
```
d = np.zeros(c.shape)
```

Another method is to simply use
```
d = 0 * c
```
Not only is this form simpler, it has the advantage that the same code will execute if c is an np.array or a float. If you try to use `c.shape` with `c` a float, Python will give an error.

Another common situation is that we want `d` to be the same size as `c`, but a constant, say 4. Using the *Zero Trick* we achieve this via
```
d = 4 + 0 * c
```
This is much simpler than using `np.zeros`. 

This occurs more frequently than you might think. You are going to need it.

---

# Review and further study

There is a lot of important material in this notebook, ... and there is a lot more to NumPy. You simply need to start using it and the most common parts will become second nature. You will need to look things up as needed. That's expected. That's how NumPy is meant to be used. No normal person memorises all the [mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html), let alone all the [NumPy routines](https://numpy.org/doc/stable/reference/routines.html).

A recent [Nature paper](https://www.nature.com/articles/s41586-020-2649-2) provides a nice overview of NumPy and its role in a broad range of scientific computations.

You will need to look things up in NumPy. We will give you some beginning practice in the exercises. In our experience, the fastest method to obtain what you want is via web search, e.g. searching `python numpy np.linspace` or even just `np.linspace` will immediately take you to the documentation you want. Maybe even try this now. The documentation may appear intimidating at first, but you do not need to understand everything.

As always, [w3shools](https://www.w3schools.com/python/numpy_intro.asp) also covers NumPy. We recommend using it for reinforcement as necessary after attempting the exercises below.


---
# Exercises

Create a code cell below each question to write your answer. 

---

### Array Basics

1. Create the following arrays using NumPy and check your results with print statements. Choose your own variable names.

- a zero vector of length 10 
- a vector with entries $2, 3, 4, \cdots, 12$ using `np.arange`.
- from the previous vector, a vector with entries $2^2, 2^3, 2^4, \cdots, 2^{12}$. (Hint: you did something similar already in this notebook.)
- similarly, a vector with entries $10^2, 10^3, 10^4, \cdots, 10^{12}$
- a zero matrix of size 3 x 4
- a 5x5 identity matrix
- a three dimensional zero array of shape (5, 7, 4). Do not print the array, but print the array shape and number of dimensions.

---
2. Use `np.linspace()` to create the following arrays. You do not need to print the full arrays, but you should check by printing at least a portion of the arrays.

- 5 equally spaced points from 0 to 1.
- 21 equally spaced points from 0 to $2\pi$.
- 100 equally spaced points from 0 to 100. Return also the step size and print it. 
- 101 equally spaced points from 0 to 100. Return also the step size and print it. (You see why I usually pick an odd number of points when using `np.linspace`.)

This would be a good opportunity to look again at the NumPy documentation on `linspace`. See that `step` is an optional return. 

---
### Arithmetic operators and math functions 


3. In order, generate the following arrays

- `x` the vector of length 101 with equally spaced values from -10 to 10.
- `y` the vector given elementwise by `x/(1+x**2)`. 

You should think of this as a discrete version of $y=f(x)$, where $f(x) = 1/(1+x^2)$.

- `t` the vector of length 101 with equally spaced values from $0$ to $2 \pi$.
- `z` the vector given elementwise by the function $\sin(t+\pi/8)$ 
- `w` the vector given elementwise by the function $e^{-t} \cos(t)$ 

After doing the Matplotlib exercises you will be able plot such arrays. This is the best way to check your work, but you can also print a few values if you want.

4. Consider the approximation to $\exp(x)$ given by

$$
e^x \simeq 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \frac{x^N}{N!} = \sum_{k=0}^N \frac{x^k}{k!} 
$$

Generate a vector `x` of length 101 with equally spaced values from -4 to 4. Set a value of `N`.  Write a `for loop` to approximate $e^x$ for all these values. You will need to search for the NumPy function for factorial. Because NumPy arithmetic operators work elementwise, the computations will look no different than if you were evaluating $e^x$ for a single float. 

Hint: you cannot initialise a variable `total` to zero as we did in the first Python code where we computed an approximation to $\pi$. Use the *Zero Trick*.


5. There are many maths functions in NumPy. For example, you may be interested in greatest common divisor (gcd) or the least common multiple (lcm). You can easily guess the names of these function. Nevertheless, search for these two and look at the NumPy documentation. 
(Note, you want the versions in the NumPy library. There is also a simpler Python math library that provides these functions. We will not be using those versions.)

Set `p` and `q` so some integer values. Print the gcd and lcm.

---
### Parameterised curves

6. We now have exactly what we need to generate parameterised curves. 

a) In Geometry and Motion you were given the parameterised curve
$$
{\bf r}(t) =(2 + \cos(3t))\, \cos(2t){\bf i}+(2 + \cos(3t))\,\sin(2t){\bf j}, 
\quad t \in [0,2\pi]
$$

which can be written in component form as:

$$
x(t) = (2 + \cos(3t)) \cos(2t) \quad
y(t) = (2 + \cos(3t)) \sin(2t), \quad t \in [0,2\pi]
$$


Write Python code to generate an np.array for t. (I suggest 101 values.) Then generate x and y. (Hint: I suggest using an auxiliary variable so that you do not repeat computations for x and y. If that makes sense, do it. If not, look at the answer below after you have answered the question.) 

b) A helix can be parameterised by 

$$
x(t) = R \cos(t) \quad
y(t) = R \sin(t), \quad
z(t) = \kappa t, \quad t \in [0,4\pi],
$$

where $R$ and $k$ are parameters. Write Python code to generate an np.array for t, and from t generate x, y and z in the case $R = 1$, $\kappa = 1/4$.

c) A semicircle in the $x=4$ plane can be parameterised by

$$
x(t) = 4 \quad
y(t) = R \sin(t), \quad
z(t) = R(1 + \cos(t)), \quad t \in [0,\pi],
$$

where $R$ is a parameter. Write Python code to generate an np.array for t, and from t generate x, y and z in the case $R = 2$. Note, you need $x$ to be an np.array of the same length as the other arrays. You will need the *Zero Trick*.

In the Matplotlib notebook you will plot these curves. 

---
# Answers and Comments
---

Expand cells (click on left margin) to see answers and any comments.


Q1 answer

In [ ]:
# Q1 answer

# I include extra lines produced by "\n" for readability 

v1 = np.zeros(10)
print(v1, "\n")

v2 = np.arange(2,13)
print(v2, "\n")

v3 = 2**v2
print(v3, "\n")

v4 = 10**v2
print(v4, "\n")

A1 = np.zeros(shape=(3,4))
print(A1, "\n")

A2 = np.eye(5)
print(A2, "\n")

T1 = np.zeros(shape=(5,7,4))
print(T1.shape)
print(T1.ndim)

Q2 answer

In [ ]:
# Q2 answer

u1 = np.linspace(0,1,5)
print(u1, "\n")

u2 = np.linspace(0,2*np.pi,21)
print(u2[:3], "\n")

u3, step3 = np.linspace(0,100,100, retstep=True)
print(u3[:3], step3, "\n")

u4, step4 = np.linspace(0,100,101, retstep=True)
print(u4[:3], step4, "\n")


Q3 answer

In [ ]:
# Q2 answer

x = np.linspace(-10,10,101)
y = x/(1+x**2)

t = np.linspace(0,2*np.pi,101)
z = np.sin(t + np.pi/8.)
w = np.exp(-t)*np.cos(t)

# what you print is up to you
print(y[0], y[50], y[100])
print(w[0])

Q4 answer

In [ ]:
# Q4 answer

N = 10
x = np.linspace(-4,4,101)

my_exp = 0 * x
for k in range(N):
    my_exp += x**k/np.math.factorial(k)

# You were not asked to test, but let's test by printing the last point
print("exp(4) is approximately", my_exp[-1], "and more precisely", np.exp(4))

Q5 answer

In [ ]:
# Q5 answer

p = 4
q = 12
print("the gcd of", p, "and", q, "is", np.gcd(p,q))
print("the lcm of", p, "and", q, "is", np.lcm(p,q))

Q6 answer

In [ ]:
# Q6 answer

# a)
# R is the auxiliary variable. 
t = np.linspace(0,2*np.pi,101)
R = 2 + np.cos(3*t)
x = R * np.cos(2*t)
y = R * np.sin(2*t)

# b) Helix
# we redefine variables and introduce kappa
R = 1
kappa = 1/4
t = np.linspace(0,4*np.pi,101)
x = R * np.cos(t)
y = R * np.sin(t)
z = kappa * t

# b)
# we again redefine variables
R = 2
t = np.linspace(0,np.pi,101)
x = 4 + 0*t
y = R * np.sin(t)
z = R * (1 + np.cos(t))

# You see how easy this is and how quickly you will be able to generate
# any parameterised curve if you can express it with basic maths functions.

---